apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"

---

apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-credentials
type: Opaque
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "user-service-db"
  POSTGRES_PORT: "5432"

--- 

apiVersion: v1
kind: Secret
metadata:
  name: ride-service-db-credentials
type: Opaque
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "ride-service-db"
  POSTGRES_PORT: "5432"